remote_theme: pmarsceill/just-the-docs
title: >
  <div style="display: flex; align-items: center; gap: 10px;">
      <img src="assets/favicon-32x32.png" alt="Cloud Freedom Logo" style="width: 40px; height: 40px;">
      <a href="/" style="text-decoration: none; color: inherit;">Cloud-Freedom</a>
  </div>
description: "Your ultimate guide to private cloud storage."
search_enabled: true
